-- Drop old tables if they exist (clean slate)
DROP TABLE IF EXISTS votes CASCADE;
DROP TABLE IF EXISTS battles CASCADE;
DROP TABLE IF EXISTS daily_rewards CASCADE;
DROP TABLE IF EXISTS user_streaks CASCADE;
DROP TABLE IF EXISTS daily_crates CASCADE;
DROP TABLE IF EXISTS xp_transactions CASCADE;
DROP TABLE IF EXISTS tournament_entries CASCADE;
DROP TABLE IF EXISTS rate_limits CASCADE;
DROP TABLE IF EXISTS cats CASCADE;
DROP TABLE IF EXISTS user_progress CASCADE;
DROP TABLE IF EXISTS streaks CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS submissions CASCADE;

-- Drop functions
DROP FUNCTION IF EXISTS initialize_new_user() CASCADE;
DROP FUNCTION IF EXISTS check_streak(UUID) CASCADE;
DROP FUNCTION IF EXISTS claim_daily_streak(UUID) CASCADE;
DROP FUNCTION IF EXISTS check_rate_limit(TEXT, INT, INT) CASCADE;
DROP FUNCTION IF EXISTS cast_vote(UUID, UUID, TEXT, UUID) CASCADE;
DROP FUNCTION IF EXISTS get_xp_for_level(INT) CASCADE;
DROP FUNCTION IF EXISTS check_level_up(UUID) CASCADE;
DROP FUNCTION IF EXISTS update_updated_at_column() CASCADE;

-- Drop triggers
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
