#!/usr/bin/env node
import fs from "node:fs/promises";
import path from "node:path";

function parseEnvFile(raw) {
  const env = {};
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    env[key] = value;
  }
  return env;
}

async function loadLocalEnv() {
  const envPath = path.resolve(process.cwd(), ".env.local");
  try {
    const raw = await fs.readFile(envPath, "utf8");
    return parseEnvFile(raw);
  } catch {
    return {};
  }
}

function getEnv(localEnv, key, fallback = "") {
  return String(process.env[key] || localEnv[key] || fallback).trim();
}

function clamp01(v) {
  const n = Number(v);
  if (!Number.isFinite(n)) return 0;
  return Math.max(0, Math.min(1, n));
}

function colorToCss(color) {
  if (!color || typeof color !== "object") return null;
  const r = Math.round(clamp01(color.r) * 255);
  const g = Math.round(clamp01(color.g) * 255);
  const b = Math.round(clamp01(color.b) * 255);
  const a = color.a == null ? 1 : clamp01(color.a);
  if (a >= 0.999) return `rgb(${r} ${g} ${b})`;
  return `rgb(${r} ${g} ${b} / ${a.toFixed(3)})`;
}

function normalizeVarName(name) {
  return String(name || "")
    .trim()
    .toLowerCase()
    .replace(/[^\w\s/-]+/g, "")
    .replace(/[\/\s]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

function fileUrl(fileKey, nodeIds) {
  const base = `https://api.figma.com/v1/files/${encodeURIComponent(fileKey)}`;
  if (!nodeIds.length) return base;
  return `${base}/nodes?ids=${encodeURIComponent(nodeIds.join(","))}`;
}

async function fetchFigmaJson(url, token) {
  const res = await fetch(url, {
    headers: {
      "X-Figma-Token": token,
      "Content-Type": "application/json",
    },
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Figma API ${res.status}: ${text.slice(0, 300)}`);
  }
  return res.json();
}

async function main() {
  const localEnv = await loadLocalEnv();
  const token = getEnv(localEnv, "FIGMA_API_TOKEN") || getEnv(localEnv, "FIGMA_TOKEN");
  const fileKey = getEnv(localEnv, "FIGMA_FILE_KEY");
  const nodeIds = getEnv(localEnv, "FIGMA_NODE_IDS")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);

  if (!token) {
    console.error("Missing FIGMA_API_TOKEN (set in .env.local).");
    process.exit(1);
  }
  if (!fileKey) {
    console.error("Missing FIGMA_FILE_KEY (set in .env.local).");
    process.exit(1);
  }

  const outDir = path.resolve(process.cwd(), "app/_lib/design");
  await fs.mkdir(outDir, { recursive: true });

  const [fileData, variablesData] = await Promise.all([
    fetchFigmaJson(fileUrl(fileKey, nodeIds), token),
    fetchFigmaJson(`https://api.figma.com/v1/files/${encodeURIComponent(fileKey)}/variables/local`, token).catch(() => null),
  ]);

  await fs.writeFile(
    path.join(outDir, "figma.raw.json"),
    JSON.stringify(fileData, null, 2),
    "utf8"
  );

  const tokens = {
    file: {
      key: fileKey,
      name: String(fileData?.name || ""),
      lastModified: String(fileData?.lastModified || ""),
      nodeScope: nodeIds,
    },
    colors: {},
    numbers: {},
    strings: {},
  };

  const cssVars = [];
  if (variablesData?.meta?.variables && variablesData?.meta?.variableCollections) {
    const vars = variablesData.meta.variables;
    const collections = variablesData.meta.variableCollections;

    for (const variableId of Object.keys(vars)) {
      const v = vars[variableId];
      const collection = collections[v.variableCollectionId];
      const defaultModeId = collection?.defaultModeId;
      const modeValue = v.valuesByMode?.[defaultModeId];
      const tokenName = normalizeVarName(v.name);
      if (!tokenName) continue;

      if (v.resolvedType === "COLOR") {
        const css = colorToCss(modeValue);
        if (!css) continue;
        tokens.colors[tokenName] = css;
        cssVars.push(`  --figma-${tokenName}: ${css};`);
      } else if (v.resolvedType === "FLOAT") {
        const num = Number(modeValue);
        if (!Number.isFinite(num)) continue;
        tokens.numbers[tokenName] = num;
        cssVars.push(`  --figma-${tokenName}: ${num};`);
      } else if (v.resolvedType === "STRING") {
        tokens.strings[tokenName] = String(modeValue ?? "");
      }
    }
  }

  await fs.writeFile(
    path.join(outDir, "figma.tokens.json"),
    JSON.stringify(tokens, null, 2),
    "utf8"
  );

  const cssOutput = [
    "/* Auto-generated by scripts/figma-sync.mjs */",
    ":root {",
    ...cssVars,
    "}",
    "",
  ].join("\n");

  await fs.writeFile(path.join(outDir, "figma.tokens.css"), cssOutput, "utf8");

  console.log(`Synced Figma file "${tokens.file.name}" (${fileKey})`);
  console.log(`- app/_lib/design/figma.raw.json`);
  console.log(`- app/_lib/design/figma.tokens.json`);
  console.log(`- app/_lib/design/figma.tokens.css`);
  if (nodeIds.length) {
    console.log(`- Scoped to node IDs: ${nodeIds.join(", ")}`);
  }
}

main().catch((err) => {
  console.error(err?.message || String(err));
  process.exit(1);
});
